2022-07-30 17:37:49,428 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.106:5000 (Press CTRL+C to quit)
2022-07-30 17:39:42,969 INFO werkzeug Thread-1 : 127.0.0.1 - - [30/Jul/2022 17:39:42] "[33mGET / HTTP/1.1[0m" 404 -
2022-07-30 17:40:01,254 INFO rest_server_app Thread-2 : application pinged...
2022-07-30 17:40:01,255 INFO werkzeug Thread-2 : 127.0.0.1 - - [30/Jul/2022 17:40:01] "GET /ping HTTP/1.1" 200 -
2022-08-31 17:06:15,319 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 17:57:54,646 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 18:10:09,751 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 18:10:09] "[33mGET /users/api/v1 HTTP/1.1[0m" 404 -
2022-08-31 18:10:18,723 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 18:10:18] "GET /users/api/v1/ping HTTP/1.1" 200 -
2022-08-31 21:41:04,916 ERROR rest_server_app Thread-3 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:41:12,090 INFO werkzeug Thread-3 : 127.0.0.1 - - [31/Aug/2022 21:41:12] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:11,023 ERROR rest_server_app Thread-4 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:11,067 INFO werkzeug Thread-4 : 127.0.0.1 - - [31/Aug/2022 21:49:11] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:19,388 ERROR rest_server_app Thread-5 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:19,389 INFO werkzeug Thread-5 : 127.0.0.1 - - [31/Aug/2022 21:49:19] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:47,681 ERROR rest_server_app Thread-6 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:49:47,682 INFO werkzeug Thread-6 : 127.0.0.1 - - [31/Aug/2022 21:49:47] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:49:58,849 INFO werkzeug Thread-7 : 127.0.0.1 - - [31/Aug/2022 21:49:58] "GET /users/api/v1/ping HTTP/1.1" 200 -
2022-08-31 21:50:16,372 ERROR rest_server_app Thread-8 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:50:16,373 INFO werkzeug Thread-8 : 127.0.0.1 - - [31/Aug/2022 21:50:16] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:50:25,526 ERROR rest_server_app Thread-9 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:50:25,527 INFO werkzeug Thread-9 : 127.0.0.1 - - [31/Aug/2022 21:50:25] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:51:33,913 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:51:38,688 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:51:38] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-08-31 21:52:19,321 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:52:25,084 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:52:25,121 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:52:25] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:54:27,470 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:54:31,737 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:54:31,739 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:54:31] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:54:48,754 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:54:51,106 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 21, in login
    print(json.dumps(user))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:54:51,111 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:54:51] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:55:16,416 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:55:18,620 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 22, in login
    print(json.dumps(user))
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:55:18,625 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:55:18] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:56:43,544 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:56:49,262 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 22, in login
    print(json.loads(user))
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2022-08-31 21:56:49,264 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:56:49] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:57:17,012 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:57:20,538 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:57:20,540 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:57:20] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:57:29,023 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    return json.dumps(user)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-08-31 21:57:29,024 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 21:57:29] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-08-31 21:59:53,625 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-08-31 21:59:57,891 INFO werkzeug Thread-1 : 127.0.0.1 - - [31/Aug/2022 21:59:57] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-08-31 22:00:08,353 INFO werkzeug Thread-2 : 127.0.0.1 - - [31/Aug/2022 22:00:08] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-02 11:30:11,331 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:31:01,310 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 24, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 63119bebd98a88de22af3253, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: [Errno 111] Connection refused')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:31:01,366 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:31:01] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:33:09,440 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 24, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119bebd98a88de22af3253, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:33:09,442 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 11:33:09] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:34:13,146 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:34:50,455 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 24, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119cdd5f2c03994325db0c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:34:50,462 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:34:50] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:35:00,451 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 11:35:00] "[31m[1mPOST /users/api/v1/ping HTTP/1.1[0m" 405 -
2022-09-02 11:36:10,969 INFO werkzeug Thread-3 : 127.0.0.1 - - [02/Sep/2022 11:36:10] "GET /users/api/v1/ping HTTP/1.1" 200 -
2022-09-02 11:36:59,793 ERROR rest_server_app Thread-4 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 24, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119cdd5f2c03994325db0c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:36:59,794 INFO werkzeug Thread-4 : 127.0.0.1 - - [02/Sep/2022 11:36:59] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:37:30,397 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:38:18,758 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 24, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119da2a0493b91106c7223, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:38:18,809 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:38:18] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:40:28,297 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:41:12,758 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:41:50,093 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read(email)
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119e80b8d907bd83a5a4e8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:41:50,100 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:41:50] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:42:21,351 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:42:57,023 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 16, in login
    user = self.users_repository.read({'email': email})
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119ec559ecb9356a696df1, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:42:57,030 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:42:57] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:46:34,945 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:47:19,526 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 25, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 17, in login
    user = self.users_repository.read({'email': email})
  File "/home/kevin/attendance-backend/src/students/students_repository.py", line 20, in read
    return self.schema.find_one(filter=document)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed,rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 63119fc2f769628174b16ba6, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('rdnc-shard-00-00.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-00.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-01.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-01.p8phn.mongodb.net:27017: connection closed')>, <ServerDescription ('rdnc-shard-00-02.p8phn.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('rdnc-shard-00-02.p8phn.mongodb.net:27017: connection closed')>]>
2022-09-02 11:47:19,556 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:47:19] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-02 11:52:38,934 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 11:52:38] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-02 11:54:33,861 INFO werkzeug Thread-3 : 127.0.0.1 - - [02/Sep/2022 11:54:33] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-02 11:57:30,270 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 11:57:52,251 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 11:57:52] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-02 12:00:45,127 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 12:00:45] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-02 12:16:44,139 ERROR rest_server_app Thread-3 : Exception on /users/api/v1/register [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 38, in register
    return jsonify({'token': token})
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-09-02 12:16:44,201 INFO werkzeug Thread-3 : 127.0.0.1 - - [02/Sep/2022 12:16:44] "[35m[1mPOST /users/api/v1/register HTTP/1.1[0m" 500 -
2022-09-02 12:19:07,520 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:19:11,259 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/register [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 37, in register
    token = users_bo.register(email=email, password=password, first_name=first_name, last_name=last_name, role=role, roll_no=roll_no, class_name=class_name)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 47, in register
    raise Exception('User %s already exist' % email)
Exception: User warnermusicunreleased@gmail.com already exist
2022-09-02 12:19:11,262 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:19:11] "[35m[1mPOST /users/api/v1/register HTTP/1.1[0m" 500 -
2022-09-02 12:20:17,693 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:20:28,421 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:20:28] "POST /users/api/v1/register HTTP/1.1" 200 -
2022-09-02 12:22:58,685 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 44, in log
    return attendance_bo.log_attendance(id=id)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 24, in log_attendance
    if (attendance['created_at']).strftime('%Y-%m-%d') != today.strftime('%Y-%m-%d'):
TypeError: 'NoneType' object is not subscriptable
2022-09-02 12:22:58,716 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 12:22:58] "[35m[1mPOST /users/api/v1/log HTTP/1.1[0m" 500 -
2022-09-02 12:24:05,057 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:24:08,073 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 44, in log
    return attendance_bo.log_attendance(id=id)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 25, in log_attendance
    if (attendance['created_at']).strftime('%Y-%m-%d') != today.strftime('%Y-%m-%d'):
TypeError: 'NoneType' object is not subscriptable
2022-09-02 12:24:08,079 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:24:08] "[35m[1mPOST /users/api/v1/log HTTP/1.1[0m" 500 -
2022-09-02 12:24:36,676 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:25:28,973 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 44, in log
    return attendance_bo.log_attendance(id=id)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 26, in log_attendance
    if (attendance['created_at']).strftime('%Y-%m-%d') != today.strftime('%Y-%m-%d'):
TypeError: 'NoneType' object is not subscriptable
2022-09-02 12:25:28,976 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:25:28] "[35m[1mPOST /users/api/v1/log HTTP/1.1[0m" 500 -
2022-09-02 12:25:54,785 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:25:57,905 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 44, in log
    return attendance_bo.log_attendance(id=id)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 26, in log_attendance
    if attendance is None and (attendance['created_at']).strftime('%Y-%m-%d') != today.strftime('%Y-%m-%d'):
TypeError: 'NoneType' object is not subscriptable
2022-09-02 12:25:57,909 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:25:57] "[35m[1mPOST /users/api/v1/log HTTP/1.1[0m" 500 -
2022-09-02 12:27:49,671 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:27:53,486 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 44, in log
    return attendance_bo.log_attendance(id=id)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 26, in log_attendance
    if attendance is None and (attendance['created_at']).strftime('%Y-%m-%d') != today.strftime('%Y-%m-%d'):
TypeError: 'NoneType' object is not subscriptable
2022-09-02 12:27:53,489 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:27:53] "[35m[1mPOST /users/api/v1/log HTTP/1.1[0m" 500 -
2022-09-02 12:28:11,784 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:28:16,165 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:28:16] "POST /users/api/v1/log HTTP/1.1" 200 -
2022-09-02 12:31:56,298 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:35:08,908 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:35:49,171 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 32, in fliter_class
    start_date = date.replace(hour=0, minute=0, second=0)
TypeError: str.replace() takes no keyword arguments
2022-09-02 12:35:49,176 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:35:49] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:35:59,559 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:36:02,400 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 32, in fliter_class
    start_date = date.replace(hour=0, minute=0, second=0)
TypeError: str.replace() takes no keyword arguments
2022-09-02 12:36:02,405 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:36:02] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:36:25,354 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:36:27,991 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    start_date = date.replace(hour=0, minute=0, second=0)
TypeError: str.replace() takes no keyword arguments
2022-09-02 12:36:27,998 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:36:27] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:36:41,469 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:36:44,821 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    start_date = date.replace(hour=0, minute=0, second=0)
TypeError: str.replace() takes no keyword arguments
2022-09-02 12:36:44,831 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:36:44] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:42:38,772 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:42:42,233 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 32, in fliter_class
    date_obj =  datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:42:42,259 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:42:42] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:42:45,471 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 32, in fliter_class
    date_obj =  datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:42:45,481 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 12:42:45] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:43:07,030 ERROR rest_server_app Thread-3 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 32, in fliter_class
    date_obj =  datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:43:07,031 INFO werkzeug Thread-3 : 127.0.0.1 - - [02/Sep/2022 12:43:07] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:43:33,829 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:43:41,853 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:43:44,717 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    date_obj = datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:43:44,721 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:43:44] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:43:55,153 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:43:56,880 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    date_obj = datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:43:56,886 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:43:56] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:44:01,161 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    date_obj = datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:44:01,162 INFO werkzeug Thread-2 : 127.0.0.1 - - [02/Sep/2022 12:44:01] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:44:36,325 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:44:40,554 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 33, in fliter_class
    date_obj = datetime.strptime(date, '%d-%m-%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%d-%m-%y'
2022-09-02 12:44:40,556 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:44:40] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:50:51,861 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:50:57,687 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 34, in fliter_class
    date_obj = datetime.strptime(date, '%d/%m/%y')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '09/19/18' does not match format '%d/%m/%y'
2022-09-02 12:50:57,707 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:50:57] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:52:06,691 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:52:11,000 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:52:11] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 12:53:08,429 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:53:12,252 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 36, in fliter_class
    date_obj = datetime.strptime(date, '%y/%m/%d')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%y/%m/%d'
2022-09-02 12:53:12,255 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:53:12] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:53:28,969 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:53:32,070 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/student_log [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 51, in get_log
    data = attendance_bo.fliter_class(name=name,date=date)
  File "/home/kevin/attendance-backend/src/attendance/attendance_bo.py", line 36, in fliter_class
    date_obj = datetime.strptime(date, '%y-%m-%d')
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-02' does not match format '%y-%m-%d'
2022-09-02 12:53:32,073 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:53:32] "[35m[1mPOST /users/api/v1/student_log HTTP/1.1[0m" 500 -
2022-09-02 12:53:56,183 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:54:01,366 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:54:01] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 12:54:29,203 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:55:01,782 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:55:08,561 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:55:08] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 12:55:40,503 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 12:55:45,358 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 12:55:45] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 14:14:47,895 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:15:24,750 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:15:38,631 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 14:15:38] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 14:20:33,613 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:20:37,512 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 14:20:37] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 14:21:38,620 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:21:48,129 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:21:52,627 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 14:21:52] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 14:33:54,685 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-02 14:34:01,966 INFO werkzeug Thread-1 : 127.0.0.1 - - [02/Sep/2022 14:34:01] "POST /users/api/v1/student_log HTTP/1.1" 200 -
2022-09-02 21:38:50,907 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:34:25,762 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:42:41,525 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:44:14,308 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 37, in login
    return self.get_token(user), user
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:44:14,367 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:44:14] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:44:43,105 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:44:43,405 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 37, in login
    print(self.get_token(user), user)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:44:43,438 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:44:43] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:45:27,027 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:45:32,582 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 38, in login
    print(self.get_token(user), user)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:45:32,585 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:45:32] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:45:58,168 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:46:03,860 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 38, in login
    print(self.get_token(user), user)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:46:03,875 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:46:03] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:46:25,239 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:46:30,581 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 38, in login
    print(self.get_token(user), user)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:46:30,586 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:46:30] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:46:51,238 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:46:53,842 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 38, in login
    return self.get_token(user), user
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:46:53,845 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:46:53] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:47:09,305 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:47:12,436 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 37, in login
    print(self.get_token(user))
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 29, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:47:12,439 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:47:12] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:47:39,532 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:47:42,529 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 38, in login
    print(self.get_token(user))
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 30, in get_token
    return jwt.encode(obj, JWT_SECRET_KEY).decode('UTF_8')
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-03 11:47:42,531 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:47:42] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-03 11:51:03,341 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:51:05,914 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:51:05] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-03 11:51:52,065 INFO auth_bo Thread-2 : Not enough segments
2022-09-03 11:51:52,066 INFO werkzeug Thread-2 : 127.0.0.1 - - [03/Sep/2022 11:51:52] "[31m[1mGET /users/api/v1/profile HTTP/1.1[0m" 401 -
2022-09-03 11:51:53,658 INFO auth_bo Thread-3 : Not enough segments
2022-09-03 11:51:53,659 INFO werkzeug Thread-3 : 127.0.0.1 - - [03/Sep/2022 11:51:53] "[31m[1mGET /users/api/v1/profile HTTP/1.1[0m" 401 -
2022-09-03 11:55:57,889 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:56:08,426 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 11:56:12,661 INFO auth_bo Thread-1 : Not enough segments
2022-09-03 11:56:12,666 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 11:56:12] "[31m[1mGET /users/api/v1/profile HTTP/1.1[0m" 401 -
2022-09-03 11:56:20,802 INFO werkzeug Thread-2 : 127.0.0.1 - - [03/Sep/2022 11:56:20] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-03 11:56:56,875 INFO auth_bo Thread-3 : Not enough segments
2022-09-03 11:56:56,880 INFO werkzeug Thread-3 : 127.0.0.1 - - [03/Sep/2022 11:56:56] "[31m[1mGET /users/api/v1/profile HTTP/1.1[0m" 401 -
2022-09-03 11:57:02,680 INFO werkzeug Thread-4 : 127.0.0.1 - - [03/Sep/2022 11:57:02] "GET /users/api/v1/profile HTTP/1.1" 200 -
2022-09-03 23:26:53,452 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 23:45:01,741 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-03 23:46:00,836 INFO werkzeug Thread-1 : 127.0.0.1 - - [03/Sep/2022 23:46:00] "GET /users/api/v1/profile HTTP/1.1" 200 -
2022-09-03 23:46:10,176 INFO werkzeug Thread-2 : 127.0.0.1 - - [03/Sep/2022 23:46:10] "GET /users/api/v1/profile HTTP/1.1" 200 -
2022-09-03 23:46:13,981 INFO werkzeug Thread-3 : 127.0.0.1 - - [03/Sep/2022 23:46:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-09-03 23:47:54,030 INFO werkzeug Thread-4 : 127.0.0.1 - - [03/Sep/2022 23:47:54] "GET /users/api/v1/profile HTTP/1.1" 200 -
2022-09-04 00:26:52,245 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 00:28:00,046 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 00:28:00] "GET /users/api/v1/profile HTTP/1.1" 200 -
2022-09-04 00:35:37,472 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 00:36:03,173 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 00:36:03] "[33mGET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1[0m" 404 -
2022-09-04 00:36:07,855 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 00:36:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-09-04 00:38:55,269 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 00:39:00,765 INFO auth_bo Thread-1 : Not enough segments
2022-09-04 00:39:00,766 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 00:39:00] "[31m[1mGET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1[0m" 401 -
2022-09-04 00:39:12,979 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 00:39:15,698 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 00:39:15] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1" 200 -
2022-09-04 01:03:53,845 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 01:03:53] "[33mGET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 01:03:54,274 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 01:03:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-09-04 01:03:57,793 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 01:03:57] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1" 200 -
2022-09-04 01:03:58,006 INFO werkzeug Thread-5 : 127.0.0.1 - - [04/Sep/2022 01:03:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-09-04 01:04:14,354 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 01:04:19,249 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 01:04:19] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 01:08:04,583 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 01:08:04] "[32mGET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1[0m" 308 -
2022-09-04 01:08:04,930 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 01:08:04] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 01:56:59,436 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 02:05:37,413 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 02:05:35] "[33mOPTIONS /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:12:16,208 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 02:12:15] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:14:43,938 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 02:14:43] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:15:46,200 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 02:15:46] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:16:46,993 INFO werkzeug Thread-5 : 127.0.0.1 - - [04/Sep/2022 02:16:46] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:18:40,400 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 02:19:03,043 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 02:19:03] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:19:50,255 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 02:19:50] "[32mGET /users/api/v1/profile/62e6c771c58ad4f71827b8d3 HTTP/1.1[0m" 308 -
2022-09-04 02:19:50,638 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 02:19:50] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 02:22:34,374 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 02:22:38,267 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 02:22:38] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 02:23:11,577 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 02:23:11] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:23:23,696 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 02:23:23] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:23:45,652 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 02:23:54,332 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 02:23:54] "[33mGET /users/api/v1/profile62e6c771c58ad4f71827b8d3/ HTTP/1.1[0m" 404 -
2022-09-04 02:24:06,700 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 02:24:06] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 02:26:33,511 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 02:26:33] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 02:31:31,335 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 02:31:31] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 03:16:05,000 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:16:05,664 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    token, user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 39, in login
    raise Exception('Invalid Credentials %s' % email)
Exception: Invalid Credentials josephkevin04@gmail.com
2022-09-04 03:16:05,704 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:16:05] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-04 03:16:11,442 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 03:16:11] "[33mPOST /users/api/v1/login/ HTTP/1.1[0m" 404 -
2022-09-04 03:16:43,396 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:16:48,696 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:16:48] "[33mPOST /users/api/v1/login/ HTTP/1.1[0m" 404 -
2022-09-04 03:17:08,731 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 03:17:08] "[33mPOST /users/api/v1/login/ HTTP/1.1[0m" 404 -
2022-09-04 03:17:11,380 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 03:17:11] "[33mPOST /users/api/v1/login/ HTTP/1.1[0m" 404 -
2022-09-04 03:17:21,166 ERROR rest_server_app Thread-4 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 27, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-09-04 03:17:21,234 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 03:17:21] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-04 03:18:30,729 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:18:31,744 ERROR rest_server_app Thread-1 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 28, in login
    return jsonify(user)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2022-09-04 03:18:31,760 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:18:31] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-04 03:19:06,596 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:19:12,694 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:19:12] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-04 03:19:59,611 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:20:09,100 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:20:09] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-04 03:21:54,924 ERROR rest_server_app Thread-2 : Exception on /users/api/v1/login [POST]
Traceback (most recent call last):
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kevin/attendance-backend/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kevin/attendance-backend/src/students/students_app.py", line 26, in login
    user = users_bo.login(email, password)
  File "/home/kevin/attendance-backend/src/students/students_bo.py", line 39, in login
    raise Exception('Invalid Credentials %s' % email)
Exception: Invalid Credentials josephkevin04@gmail.com
2022-09-04 03:21:54,951 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 03:21:54] "[35m[1mPOST /users/api/v1/login HTTP/1.1[0m" 500 -
2022-09-04 03:22:01,247 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 03:22:01] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-04 03:25:32,094 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 03:27:15,034 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 03:27:15] "POST /users/api/v1/login HTTP/1.1" 200 -
2022-09-04 04:00:34,759 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 05:18:15,101 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 05:19:45,670 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 05:19:45] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 05:22:10,440 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 05:22:10] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 05:22:11,310 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 05:22:11] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 05:22:30,867 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 05:22:30] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 05:23:55,199 INFO werkzeug Thread-5 : 127.0.0.1 - - [04/Sep/2022 05:23:55] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 05:24:30,013 INFO werkzeug Thread-6 : 127.0.0.1 - - [04/Sep/2022 05:24:30] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 05:30:16,410 INFO werkzeug Thread-7 : 127.0.0.1 - - [04/Sep/2022 05:30:16] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 05:30:16,832 INFO werkzeug Thread-8 : 127.0.0.1 - - [04/Sep/2022 05:30:16] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 11:17:48,407 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 11:42:02,680 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 11:42:02] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 11:47:45,792 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 11:47:45] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-04 11:47:48,439 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 11:47:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-09-04 12:14:16,663 INFO werkzeug Thread-5 : 127.0.0.1 - - [04/Sep/2022 12:14:16] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 12:52:58,408 INFO werkzeug Thread-6 : 127.0.0.1 - - [04/Sep/2022 12:52:58] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 14:22:45,696 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-04 14:23:08,519 INFO werkzeug Thread-1 : 127.0.0.1 - - [04/Sep/2022 14:23:08] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 14:23:34,677 INFO werkzeug Thread-2 : 127.0.0.1 - - [04/Sep/2022 14:23:34] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 15:20:53,266 INFO werkzeug Thread-3 : 127.0.0.1 - - [04/Sep/2022 15:20:53] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:26:14,628 INFO werkzeug Thread-4 : 127.0.0.1 - - [04/Sep/2022 16:26:14] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:29:17,016 INFO werkzeug Thread-5 : 127.0.0.1 - - [04/Sep/2022 16:29:17] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:29:46,160 INFO werkzeug Thread-6 : 127.0.0.1 - - [04/Sep/2022 16:29:46] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:29:56,860 INFO werkzeug Thread-7 : 127.0.0.1 - - [04/Sep/2022 16:29:56] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:41:28,178 INFO werkzeug Thread-8 : 127.0.0.1 - - [04/Sep/2022 16:41:28] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:50:42,858 INFO werkzeug Thread-9 : 127.0.0.1 - - [04/Sep/2022 16:50:42] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 16:50:44,150 INFO werkzeug Thread-10 : 127.0.0.1 - - [04/Sep/2022 16:50:44] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:50:53,410 INFO werkzeug Thread-11 : 127.0.0.1 - - [04/Sep/2022 16:50:53] "[32mPOST /users/api/v1/login HTTP/1.1[0m" 308 -
2022-09-04 16:50:53,651 INFO werkzeug Thread-12 : 127.0.0.1 - - [04/Sep/2022 16:50:53] "POST /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 16:50:58,051 INFO werkzeug Thread-13 : 127.0.0.1 - - [04/Sep/2022 16:50:58] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-04 17:45:40,048 INFO werkzeug Thread-15 : 127.0.0.1 - - [04/Sep/2022 17:45:39] "OPTIONS /users/api/v1/login/ HTTP/1.1" 200 -
2022-09-05 18:28:26,693 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-05 18:30:05,344 INFO werkzeug Thread-1 : 127.0.0.1 - - [05/Sep/2022 18:30:05] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-05 19:35:13,254 INFO werkzeug Thread-2 : 127.0.0.1 - - [05/Sep/2022 19:35:13] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-05 19:37:49,850 INFO werkzeug Thread-3 : 127.0.0.1 - - [05/Sep/2022 19:37:49] "GET /users/api/v1/profile/62e6c771c58ad4f71827b8d3/ HTTP/1.1" 200 -
2022-09-05 20:17:34,792 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
2022-09-05 20:55:45,598 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.126:5000 (Press CTRL+C to quit)
